version: '3.8'

services: 
  bowii-dev-container:
    build: .
    image: bowii-dev-container
    container_name: bowii-dev-container
    volumes:
      - ../:/workspace
    ports:
      - "8080:8080"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      
    command: /bin/sh -c "while sleep 1000; do :; done"