FROM mcr.microsoft.com/vscode/devcontainers/cpp:ubuntu-20.04

WORKDIR /workspace

RUN apt-get update -y \
    && apt-get install build-essential -y \
    && apt-get install cmake -y

RUN apt-get install libgtest-dev -y
RUN cd /usr/src/gtest && \
    sudo cmake CMakeLists.txt && sudo make
RUN sudo cp /usr/src/gtest/lib/*.a /usr/lib



